#!/usr/bin/env ruby
# frozen_string_literal: true

puts 'Tic-Tac-Toe Game'
puts 'In this game, wins that who can mark three numbers in a sequence.'
puts "Players take turns to mark the numbers. The first will have X's as marks,"
puts "the second will have O's."
puts 'They can be in diagonal, horizontal or vertical alignment.'
puts 'If no number can be chosen, and no three numbers in sequence were chosen,'
puts "then there's no winner, and the game ends."

print "Player 1's name: "
player_1 = gets.chomp.to_s
print "Player 2's name: "
player_2 = gets.chomp.to_s

puts ' *****************'

puts 'Let the game begin!'

puts ' *****************'

[[" 1 | 2 | 3 "], [" 4 | 5 | 6 "], [" 7 | 8 | 9 "]].each { |x| puts x }

puts 'To play, choose a number'

choice = gets.chomp.to_s


puts "It's #{player_1}'s turn"
puts "It's #{player_2}'s turn"

winner = 'Nobody'

puts "#{winner} won!"
